### PR TITLE
[WIP] Added accessibility tests

### LINKED ISSUE #679: [pi] First iteration of automated accessibility checks
Integrate PI's axe-core api into the integration suite to provide regression checks for accessibility requirements. The PR will provide an opening for discussions around enhancements we may wish to make to the app as will as provide information on which tests should be included in the TravisCI build or offloaded to PI's Jenkins env.

Important as well, this will provide information on what should block the build vs. act as information.

### PR DESCRIPTION
**Pull request by kimberlythegeek**
Work in Progress, do not merge.

This build will currently fail due to critical accessibility violations. For more info, view the travis console output.

* Added a Travis environment for the new accessibility tests
* Added locators to be used in accessibility tests
* A couple of nits, replaced `url` or `website` with `site_url` in a few places for consistency
* Added more properties inline with the `title` property, as getter methods, essentially
* Modified `test_add_entry_as_guest` to create a non-empty entry, and check that all values are as expected
* Added a tox environment for accessibility tests

Fixes #679

### CODE REVIEW

**Comment by kimberlythegeek** [comment]
@m8ttyB r?

**Comment by jimporter** [comment]
I haven't looked at every failure, but a few stand out as very easy to fix. I'll try and get the tests passing before we merge this.

**Comment by kimberlythegeek** [comment]
Thanks @jimporter!

**Comment by jimporter** [comment]
@kimberlythegeek It took longer than I'd hoped (I was blocked with some `fluent` issues), but I've rebased this and fixed the failing tests in #709. Thanks for writing the initial tests; they helped find some real issues in our code, and they were thankfully fairly easy to diagnose/fix!

**Comment by devinreams** [comment]
Replaced by #709

**Pull request closed without merging**
