### PR TITLE
Add a top-border above the item list in the manager

### PR DESCRIPTION
**Pull request by jimporter**
Depends on #619 

This is based on #619, and just fixes a little thing I noticed during review, but which is out-of-scope for that PR. Since I didn't want to start causing scope creep there, here's a tiny PR to fix things. Only the last commit is relevant.

### CODE REVIEW

**Comment by jimporter** [comment]
Note: this has r+ and ui-r+; just waiting on the parent PR to merge before I merge this.

**Comment by nickbrandt** [comment]
@jimporter We had removed this border in #553 until we redid the filter area. Can we instead apply the border to the first entry list item, as that would make it easier to change the border color for that entry on active state? I had actually implemented that change back in #657 , and you can see there how it's currently working. I can strip that out now knowing there is this issue in place already, but wanted to see if we can add the border in that manner instead.

**Comment by jimporter** [comment]
@nickbrandt See my comments on your PR for this. However, the tl;dr is that I think we probably want this border to *not* be attached to the first item.

**Comment by devinreams** [comment]
@jimporter @nickbrandt Now that #619 is merged this is ready for rebase (see conflicts) and merge, assuming you all are.

**Comment by jimporter** [comment]
@changecourse Just wanted to get one last peek at this to make sure this is what you wanted for the "double border".

**Comment by jimporter** [comment]
@changecourse That does mean there's *no dividing line* between the search box and the item list when scrolled down past the first item. Is that what you want?

**Comment by changecourse** [comment]
@jimporter agh, right... yeah, not my intent either.

What about the option #3 then, as referenced from your previous comments on this... 

> 3. Instead of using a bottom-border on the header, give it a box-shadow on the bottom with a higher z-index than the list, and give focused/selected items an even higher z-index; this will look slightly off when a focused/selected item is partially scrolled out of view though

Could this approach work for both the doorhanger and full tab management view?

**Comment by jimporter** [comment]
@changecourse Ok, I think I actually have a "perfect" solution, but it's somewhat messy and will require moving a few things around. I'll do this in the PR I'm working on to remove the main toolbar from the management tab (since I'm already making some changes there that make this much easier).

**Pull request closed without merging**
