### PR TITLE
Update dependencies to all the latest versions

### PR DESCRIPTION
**Pull request by jimporter**
It's almost time for another release, so let's update our dependencies! Tested locally and everything seems to work (and tests pass, of course).

### CODE REVIEW

**Comment by m8ttyB** [comment]
What's the risk associated with this, what value does it add? 

Will we need to do full run of the e2e tests? If so, I'd like hold this until next release.

**Comment by jimporter** [comment]
They're all minor/patch releases (except codecov, which is a major release), and all except `react-modal` are dev-only packages. `react-modal` has some small enhancements to its focusing logic that shouldn't affect us.

**Comment by m8ttyB** [comment]
Today is code freeze, unless it solves a known bug or adds required functionality, I'm r-.

**Comment by devinreams** [comment]
Good points made here. And as discussed today, how about we agree:

- watch for back-end updates that need to be updated as needed (sooner than later)
- do dependency updates at _beginning_ of dev cycle to catch any unexpected results/bugs

@linuxwolf to re-review/clear.

**Pull request merged**
