### PR TITLE
Updating entry list items, account dropdown, and quick copy button hover/press/active/focus states due to conflicting grays.

### LINKED ISSUE #653: DR: hover and pressed states for clickable elements (entry and action btns)
Problem: hover state matches the doorhanger/entry list container color, due to the colors we presently have to work with in the Photon spec. 

The current photon spec does not give us enough flexibility for handling explicit hover and pressed states of these items relative to their containers, which use some of the same colors (shades of grey 10, 20, and 30)

Because of this, we wish to divert from the spec and embrace some of the work we've been doing with the blue tint for the active state, and incorporate lighter shades of it into replacement hover/press styles. 

Still finalizing colors for review.

**Tasks**
- [x] Entry Items
- [x] Entry Action Buttons
- [x] Account Dropdown

### PR DESCRIPTION
**Pull request by nickbrandt**
Resolves #653 
Depends on #619

This fixes the issue we noticed with different item/button states not being visible enough or appearing broken due to surrounding grays on the page. We have opted to use shades of Blue50 to resolve this.

Note: This PR includes updates from a branch not yet merged in from #483 , so this only applies to the additions around the state color changes.

### CODE REVIEW

**Comment by nickbrandt** [comment]
states-update

**Comment by jimporter** [comment]
Have we brought these issues up with the Photon team yet? Maybe these are changes they'd like to make to the spec as a whole (or maybe they've run into similar issues and could help us out in some other way). I checked briefly, but didn't see any issues on this in the Photon repo, so it's hard to tell if they're aware.

**Comment by changecourse** [comment]
@jimporter It's on my list to discuss with them during our next touch base with the team.

**Comment by devinreams** [comment]
@jimporter @nickbrandt Now that #619 is merged this is ready for a rebase or merge from `master` and conflicts fixed.

**Comment by nickbrandt** [comment]
@devinreams On it!

**Comment by devinreams** [comment]
Marking this as a candidate for 0.1.9 release.

This assumes the a final 👍 review from @jimporter within the next day or so...

**Pull request merged**
