### PR TITLE
The Great Renaming

### PR DESCRIPTION
**Pull request by jimporter**
This renames all our files to use hyphens instead of camelCase. That's more conventional and should avoid any problems on case-insensitive file systems. I also did the same for our CSS class names since that's the prevailing style in CSS.

### CODE REVIEW

**Comment by devinreams** [comment]
After `npm install` and `npm run run` I got an error:

```
ERROR in ../node_modules/fluent-intl-polyfill/src/index.js
Module not found: Error: Can't resolve 'intl-pluralrules' in '/Users/dreams/src/lockbox-extension/node_modules/fluent-intl-polyfill/src'
 @ ../node_modules/fluent-intl-polyfill/src/index.js 9:0-58
 @ ./webextension/l10n.js
 @ ./webextension/manage/index.js
```

I removed `node_modules` and the package-lock 🔒then install'd and run'd again with success ✅ 

(any good way to prevent all that? is it expected I'd have to do that?)

**Comment by jimporter** [comment]
That's weird. It shouldn't do that; `npm install` should be sufficient. (That change is technically from #58, not this PR though.)

**Comment by jimporter** [comment]
@linuxwolf or @devinreams: review ping?

**Comment by jimporter** [comment]
Merging without another review since all I did was rebase onto master.

**Pull request merged**
