### PR TITLE
Initial pyup Update

### LINKED ISSUE #291: Add python dependency updater.
It would be nice to keep the Integration tests dependencies updated. We usually use https://github.com/pyupio/pyup and it will add commits on my behalf (if I am the person who sets it up), when new versions of the dependencies are updated.

See this PR as an example: https://github.com/mozilla/FoxPuppet/pull/128

### PR DESCRIPTION
**Pull request by devinreams**
Fixes #291 
## Updates
Here's a list of all the updates bundled in this pull request.
<table align="center">

<tr>
<td><b>pytest-xdist</b></td>
<td align="center">1.18.2</td>
<td align="center">&raquo;</td>
<td align="center">1.20.1</td>

<tr>
<td><b>pytest-selenium</b></td>
<td align="center">1.11.0</td>
<td align="center">&raquo;</td>
<td align="center">1.11.2</td>

<tr>
<td><b>selenium</b></td>
<td align="center">3.6.0</td>
<td align="center">&raquo;</td>
<td align="center">3.8.0</td>

<tr>
<td><b>pytest</b></td>
<td align="center">3.2.2</td>
<td align="center">&raquo;</td>
<td align="center">3.3.0</td>

</tr>
</table>

---
*Running the bot with an API key allows it to query pyup.io's API for changelogs and insecure packages. This is highly recommended for production use. [Learn More](https://pyup.io/docs/api-key/)*

### CODE REVIEW

**Comment by jrbenny35** [comment]
Pytest might fail as it needs some extra deps, but I think it will install them.

**Comment by devinreams** [comment]
>Pytest might fail as it needs some extra deps, but I think it will install them.

@jrbenny35 the bad news: It did fail. 😔 

The good news: everything else is still green. ✅ 

Can you tell why/what needs to change?
https://travis-ci.org/mozilla-lockbox/lockbox-extension/builds/311427046

**Comment by jrbenny35** [comment]
It looks like the tab just didn't open in time, which is weird.

**Comment by devinreams** [comment]
>It looks like the tab just didn't open in time, which is weird.

Ah, I manually re-ran the test just to make sure it's not a fluke. We're all green now. ✅ 

```
test/integration/tests/test_lockbox.py::test_login PASSED                [ 33%]

test/integration/tests/test_lockbox.py::test_add_entry PASSED            [ 66%]

test/integration/tests/test_lockbox.py::test_delete_entry PASSED         [100%]
```

@jrbenny35 I assume you're 👍 good with us merging this?

@jimporter I assume you don't have any concerns with bumping these dependencies?

**Comment by jrbenny35** [comment]
Looks good here. I'll have to monitor that fluke and maybe extend the timeout a bit.

**Comment by devinreams** [comment]
@jrbenny35 sorry for letting this fall behind. Now that there's a conflict, can you please confirm the version numbers you want bumped up to?

**Comment by jrbenny35** [comment]
These are good. I think you can close the PR and it will open another, or just use the "Resolve Conflicts" button on the Guthub UI.

**Pull request closed without merging**
