### PR TITLE
Set up a release with disclaimers about active development

### LINKED ISSUE #740: Publish a final version of the extension to communicate expectations
To consider tagging and releasing once more as a follow up to #738:

- note that future development is on hold in the description
- explain this is separate from "saved logins" in browser
- drive users to mobile apps?

### PR DESCRIPTION
**Pull request by devinreams**
Resolves #740 
 
To be explained in more detail elsewhere. For now, this PR:

- creates an 0.1.10-alpha realase that includes the latest code
- adds a disclaimer to the extension name
- adds a disclaimer to the extension settings page, home page, and first run

screen shot 2018-08-07 at 2 08 33 pm
screen shot 2018-08-07 at 2 08 55 pm
screen shot 2018-08-07 at 2 11 20 pm

@sandysage I'll hold off on releasing this until you give your approval. Let me know if you'd like anything else changed.

### CODE REVIEW

**Comment by linuxwolf** [comment]
I'm wondering if a disclaimer in the management interface is also warranted ...  I'm personally unsure.

**Comment by devinreams** [comment]
>I'm wondering if a disclaimer in the management interface is also warranted

I thought about it, too.

Perhaps on the "welcome" getting started screen beneath the tagline and maybe on the "home" screen with lockie?

**Comment by devinreams** [comment]
OK I've updated the string and dropped it onto the "first run" and "homepage" screens:

screen shot 2018-08-07 at 2 08 33 pm
screen shot 2018-08-07 at 2 08 55 pm

**Comment by devinreams** [comment]
Approved by @sandysage in Slack. 🤘

**Pull request merged**
