### PR TITLE
Refactor telemetry

### LINKED ISSUE #358: Update Telemetry events to conform to doorhanger metrics specs
The new "doorhanger" was added at #338 (hidden/disabled except in dev modes) and new metrics specs added at #342.

Now that the two are in place, the Telemetry events need to be updated to distinguish those happening in the doorhanger.

- [ ] render event
- [ ] "Manage Lockbox" button (not in metrics.md spec)
- [ ] doorhangerItemSelected
- [ ] doorhangerItemCopied
- doorhangerAddClick (does not yet exist #354)

Does that look right @irrationalagent? You mentioned you wanted to take a stab 🔪 at this first so I set you as assignee.

### PR DESCRIPTION
**Pull request by jimporter**
This is based on #361, so ignore the first two commits.

Resolves #358

### CODE REVIEW

**Comment by jimporter** [comment]
This is basically done, but not fully-tested yet. Let me know if the telemetry changes look good.

**Comment by irrationalagent** [comment]
not sure if you were ready for a test but just quickly tried this branch out locally. on npm run run i got this warning:

`lockbox-extension/src/webextension/list/popup/index.js
  24:1  warning  'telemetry' is not defined  no-undef`

and clicking new item from the manager no longer works. my console log is below


<details><summary>click for log</summary>
<p>
OpenGL compositor Initialized Succesfully.
Version: 2.1 ATI-1.51.8
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 460 OpenGL Engine
FBO Texture Target: TEXTURE_2D
ReferenceError: reference to undefined property "app-temporary"[Learn More]  XPIProvider.jsm:1569:1
1512517129586	addons.xpi	WARN	Please specify whether you want browser_style or not in your options_ui options.
ReferenceError: reference to undefined property "applySoftBlock"[Learn More]  XPIProvider.jsm:5049:9
ReferenceError: reference to undefined property "version"[Learn More]  XPIProvider.jsm:2777:32
ReferenceError: reference to undefined property "placeholders"[Learn More]  ExtensionCommon.jsm:1481:1
ReferenceError: reference to undefined property "disabled"[Learn More]  CustomizableUI.jsm:2458:5
TypeError: useless expression  buildSettings.js:10
1512517130163	addons.webextension.lockbox@mozilla.com	WARN	Please specify whether you want browser_style or not in your browser_action options.
ReferenceError: reference to undefined property "additionalBackgrounds"[Learn More]  LightweightThemeConsumer.jsm:159:5
ReferenceError: reference to undefined property "backgroundsAlignment"[Learn More]  LightweightThemeConsumer.jsm:202:5
ReferenceError: reference to undefined property "initialPageLoadedFromURLBar"[Learn More]  tabbrowser.xml:739:1
OpenGL compositor Initialized Succesfully.
Version: 2.1 ATI-1.51.8
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 460 OpenGL Engine
FBO Texture Target: TEXTURE_2D
ReferenceError: reference to undefined property "viewId"[Learn More]  CustomizableUI.jsm:1513:51
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  background.js:21045:51
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  background.js:21056:54
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  background.js:36488:19
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  background.js:36518:19
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  background.js:64038:21
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  background.js:71171:41
ReferenceError: reference to undefined property "presence"[Learn More]  background.js:42291:1
ReferenceError: reference to undefined property "presence"[Learn More]  background.js:48079:1
ReferenceError: reference to undefined property "Buffer"[Learn More]  background.js:5739:5
ReferenceError: reference to undefined property "Buffer"[Learn More]  background.js:51304:5
ReferenceError: reference to undefined property "process"[Learn More]  background.js:53293:1
ReferenceError: reference to undefined property "__isLong__"[Learn More]  background.js:20995:5
ReferenceError: reference to undefined property "buffer"[Learn More]  background.js:374:1
ReferenceError: reference to undefined property "getCryptoParams"[Learn More]  PushService.jsm:23:5
ReferenceError: reference to undefined property "NODE_ENV"[Learn More]  Redux.jsm:739:1
ReferenceError: reference to undefined property "NODE_ENV"[Learn More]  Redux.jsm:1161:1
ReferenceError: reference to undefined property "NODE_ENV"[Learn More]  Redux.jsm:1192:1
ReferenceError: reference to undefined property "geo"[Learn More]  ActivityStream.jsm:293:1
ReferenceError: reference to undefined property "config"[Learn More]  background.js:23601:1
loaded authorization for ''  background.js:38578:5
SyntaxError: test for equality (==) mistyped as assignment (=)?  react-intl.js:8:341
SyntaxError: test for equality (==) mistyped as assignment (=)?  react-intl.js:8:23093
SyntaxError: test for equality (==) mistyped as assignment (=)?  react-intl.js:8:27029
ReferenceError: reference to undefined property "[object Object]"  activity-stream.bundle.js:1657:68
ReferenceError: reference to undefined property "initialNow"  react-intl.js:9:1884
ReferenceError: reference to undefined property "$$typeof"  react-dom.js:15:19504
ReferenceError: reference to undefined property "value"  react-dom.js:12:29378
ReferenceError: reference to undefined property "checked"  react-dom.js:12:29456
ReferenceError: reference to undefined property "children"  activity-stream.bundle.js:766:1
ReferenceError: reference to undefined property "type"  activity-stream.bundle.js:3234:11
ReferenceError: reference to undefined property "version"[Learn More]  LoginStore.jsm:112:1
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.  (unknown)
ReferenceError: reference to undefined property "componentDidUpdate"  react-dom.js:13:9781
ReferenceError: reference to undefined property "type"  activity-stream.bundle.js:2207:47
ReferenceError: reference to undefined property "children"  activity-stream.bundle.js:2739:1
ReferenceError: reference to undefined property "_self"  react.js:12:11225
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:6415
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:6641
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:7897
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:9774
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:11336
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:11912
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:11950
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:12911
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:13223
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:15044
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:15308
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:15456
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:16528
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:18859
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:18948
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:19008
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:20291
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:20851
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:1:20959
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:2:19867
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:2:19994
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:3:2158
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:3:4620
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:3:10695
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:3:13890
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:3:14334
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:3:14748
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:3:17037
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:3:19530
SyntaxError: test for equality (==) mistyped as assignment (=)?  common-bundle.0a1cc8682dee.js:3:21432
ReferenceError: reference to undefined property "expando"  common-bundle.0a1cc8682dee.js:2:4652
ReferenceError: reference to undefined property "$$typeof"  react.js:12:18297
ReferenceError: reference to undefined property "jQuery111304529782634234383"  common-bundle.0a1cc8682dee.js:2:97
ReferenceError: reference to undefined property "type"  common-bundle.0a1cc8682dee.js:3:8854
ReferenceError: reference to undefined property "nodeName"  common-bundle.0a1cc8682dee.js:1:31491
ReferenceError: reference to undefined property "triggered"  common-bundle.0a1cc8682dee.js:2:6886
ReferenceError: reference to undefined property "undefined"  common-bundle.0a1cc8682dee.js:2:1051
ReferenceError: reference to undefined property "image"  activity-stream.bundle.js:3225:1
ReferenceError: reference to undefined property "_defaultEngine"  contentSearchUI.js:76:5
SyntaxError: test for equality (==) mistyped as assignment (=)?  gtm.js:91:307
ReferenceError: reference to undefined property "reset"[Learn More]  ProfileAge.jsm:203:16
SyntaxError: test for equality (==) mistyped as assignment (=)?  gtm.js:99:131
SyntaxError: test for equality (==) mistyped as assignment (=)?  gtm.js:100:285
SyntaxError: test for equality (==) mistyped as assignment (=)?  gtm.js:118:263
SyntaxError: test for equality (==) mistyped as assignment (=)?  gtm.js:122:417
ReferenceError: reference to undefined property "triggered"  common-bundle.0a1cc8682dee.js:2:5184
ReferenceError: reference to undefined property "result"  common-bundle.0a1cc8682dee.js:2:8689
ReferenceError: reference to undefined property "event"  common-bundle.0a1cc8682dee.js:4:30787
ReferenceError: reference to undefined property "gtm"  gtm.js:39:167
ReferenceError: reference to undefined property "eventCallback"  gtm.js:69:467
ReferenceError: reference to undefined property "gtm.gtm.whitelist"  gtm.js:55:30
ReferenceError: reference to undefined property 17  gtm.js:11:146
ReferenceError: reference to undefined property 16  gtm.js:10:222
ReferenceError: reference to undefined property 17  gtm.js:21:451
ReferenceError: reference to undefined property 17  gtm.js:28:154
ReferenceError: reference to undefined property ""  gtm.js:124:133
ReferenceError: reference to undefined property ""  gtm.js:13:104
SyntaxError: test for equality (==) mistyped as assignment (=)?  analytics.js:6:542
SyntaxError: test for equality (==) mistyped as assignment (=)?  analytics.js:15:204
SyntaxError: test for equality (==) mistyped as assignment (=)?  analytics.js:39:1236
SyntaxError: test for equality (==) mistyped as assignment (=)?  analytics.js:41:437
SyntaxError: test for equality (==) mistyped as assignment (=)?  analytics.js:41:495
SyntaxError: test for equality (==) mistyped as assignment (=)?  analytics.js:43:204
SyntaxError: test for equality (==) mistyped as assignment (=)?  analytics.js:44:100
ReferenceError: reference to undefined property ":linker"  analytics.js:5:248
ReferenceError: reference to undefined property 2  analytics.js:48:1196
ReferenceError: reference to undefined property "W"  analytics.js:54:444
ReferenceError: reference to undefined property "t0"  analytics.js:57:226
ReferenceError: reference to undefined property "cookieName"  analytics.js:40:625
ReferenceError: reference to undefined property "W"  analytics.js:55:229
SyntaxError: test for equality (==) mistyped as assignment (=)?  linkid.js:1:1283
ReferenceError: reference to undefined property 0  analytics.js:1:171
SyntaxError: 'use strict' statement won't be enforced as a directive because it isn't in directive prologue position  newtab:14:1
ReferenceError: reference to undefined property "testpilotAddon"  newtab:132:13
1512517132657	Toolkit.Telemetry	WARN	TelemetryEnvironment::setExperimentActive - the experiment type was truncated.
ReferenceError: reference to undefined property "overrideEndpointPref"[Learn More]  PingCentre.jsm:42:5
ReferenceError: reference to undefined property "customizemode"[Learn More]  SessionStore.jsm:4445:1
ReferenceError: reference to undefined property "_firstSession"  onboarding.js:887:1
ReferenceError: reference to undefined property "resume"[Learn More]  node-properties.js:134:15
ReferenceError: reference to undefined property "o"[Learn More]  node-properties.js:124:7
ReferenceError: reference to undefined property "o"[Learn More]  node-properties.js:130:7
ReferenceError: reference to undefined property "type"[Learn More]  debugger-client.js:894:9
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  react-dom.js:6709:48
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  react-dom.js:10522:47
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  react-dom.js:17300:55
TypeError: Symbol.toStringTag is read-only[Learn More]  lodash.js:6028:9
ReferenceError: reference to undefined property "$$typeof"[Learn More]  react.js:2067:10
ReferenceError: reference to undefined property "propTypes"[Learn More]  react.js:4319:7
ReferenceError: reference to undefined property "autobind"[Learn More]  react.js:4449:1
ReferenceError: reference to undefined property "type"[Learn More]  HTMLTooltip.js:222:1
ReferenceError: reference to undefined property "width"[Learn More]  HTMLTooltip.js:305:1
OpenGL compositor Initialized Succesfully.
Version: 2.1 ATI-1.51.8
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 460 OpenGL Engine
FBO Texture Target: TEXTURE_2D
ReferenceError: reference to undefined property "level"[Learn More]  webconsole.js:2115:1
ReferenceError: reference to undefined property "$$typeof"[Learn More]  react-dom.js:16929:1
ReferenceError: reference to undefined property "screenX"[Learn More]  panelUI.js:382:9
ReferenceError: reference to undefined property 0[Learn More]  PanelMultiView.jsm:97:5
Intl.PluralRules already exists, and has NOT been replaced by this polyfill  index.js:24991:5
To force, set a global ClobberIntlPluralRules = true  index.js:24992:5
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  index.js:10696:41
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  index.js:21047:51
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  index.js:21873:46
ReferenceError: reference to undefined property "get"[Learn More]  index.js:8400:3
ReferenceError: reference to undefined property "unstable_isAsyncReactComponent"[Learn More]  index.js:17844:1
ReferenceError: reference to undefined property "unstable_isAsyncReactComponent"[Learn More]  index.js:13097:1
ReferenceError: reference to undefined property "functions"[Learn More]  index.js:23917:1
ReferenceError: reference to undefined property 990[Learn More]  index.js:1444:1
ReferenceError: reference to undefined property 990[Learn More]  index.js:1569:1
ReferenceError: reference to undefined property "props"[Learn More]  index.js:12987:11
ReferenceError: reference to undefined property "type"[Learn More]  index.js:14292:9
ReferenceError: reference to undefined property "error"[Learn More]  index.js:22399:11
ReferenceError: reference to undefined property "_valueTracker"[Learn More]  index.js:9132:3
ReferenceError: reference to undefined property "$$typeof"[Learn More]  index.js:6053:1
ReferenceError: reference to undefined property "get"[Learn More]  index.js:8072:1
ReferenceError: reference to undefined property "get"[Learn More]  index.js:8033:7
ReferenceError: reference to undefined property "window"[Learn More]  index.js:10855:9
ReferenceError: reference to undefined property "get"[Learn More]  index.js:7626:7
ReferenceError: reference to undefined property "get"[Learn More]  index.js:8364:9
ReferenceError: reference to undefined property "timeStyle"[Learn More]  mozIntl.js:84:1
ReferenceError: reference to undefined property "get"[Learn More]  index.js:8471:1
ReferenceError: reference to undefined property "get"[Learn More]  index.js:8278:7
ReferenceError: reference to undefined property "get"[Learn More]  index.js:8059:5
ReferenceError: reference to undefined property "get"[Learn More]  index.js:22354:7
ReferenceError: reference to undefined property "fromElement"[Learn More]  index.js:9549:5
ReferenceError: reference to undefined property "keystore"[Learn More]  background.js:14402:7
ReferenceError: reference to undefined property "kty"[Learn More]  background.js:51770:31
Intl.PluralRules already exists, and has NOT been replaced by this polyfill  index.js:24717:5
To force, set a global ClobberIntlPluralRules = true  index.js:24718:5
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  index.js:10989:41
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  index.js:21340:51
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  index.js:22166:46
ReferenceError: reference to undefined property "get"[Learn More]  index.js:8693:3
ReferenceError: reference to undefined property "@@toStringTag"[Learn More]  index.js:23344:1
ReferenceError: reference to undefined property "unstable_isAsyncReactComponent"[Learn More]  index.js:18137:1
ReferenceError: reference to undefined property "unstable_isAsyncReactComponent"[Learn More]  index.js:13390:1
Error: Unknown event: ["lockboxv0", "lockbox", "click"]  undefined
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 514"  data: no]  (unknown)
ReferenceError: reference to undefined property "functions"[Learn More]  index.js:23649:1
ReferenceError: reference to undefined property 2478[Learn More]  index.js:1976:1
ReferenceError: reference to undefined property 2478[Learn More]  index.js:2101:1
ReferenceError: reference to undefined property "props"[Learn More]  index.js:13280:11
ReferenceError: reference to undefined property "type"[Learn More]  index.js:14585:9
ReferenceError: reference to undefined property "store"[Learn More]  index.js:26604:9
ReferenceError: reference to undefined property "dependsOnOwnProps"[Learn More]  index.js:27152:3
ReferenceError: reference to undefined property "type"[Learn More]  index.js:24170:1
ReferenceError: reference to undefined property "_valueTracker"[Learn More]  index.js:9425:3
ReferenceError: reference to undefined property "get"[Learn More]  index.js:8764:1
ReferenceError: reference to undefined property "get"[Learn More]  index.js:8365:1
ReferenceError: reference to undefined property "get"[Learn More]  index.js:8326:7
ReferenceError: reference to undefined property "window"[Learn More]  index.js:11148:9
ReferenceError: reference to undefined property "get"[Learn More]  index.js:7919:7
ReferenceError: reference to undefined property "get"[Learn More]  index.js:8657:9
ReferenceError: reference to undefined property "fromElement"[Learn More]  index.js:9842:5
ReferenceError: reference to undefined property "get"[Learn More]  index.js:8352:5
ReferenceError: reference to undefined property "get"[Learn More]  index.js:8571:7
ReferenceError: reference to undefined property "end_timestamp"[Learn More]  GCTelemetry.jsm:58:7

</p>
</details>

just fyi in case that helps

**Comment by devinreams** [comment]
>not sure if you were ready for a test but just quickly tried this branch out locally
>and clicking new item from the manager no longer works. my console log is below

@irrationalagent @jimporter I get the same.

> Let me know if the telemetry changes look good.

The middlware and changes look really straight forward. Cooooool 😎

**Comment by devinreams** [comment]
@jimporter for PM purposes I'm going to mark this as "resolves #358" (doorhanger telemetry) per 44eef2e even though this PR obviously does much more than that.

**Comment by devinreams** [comment]
@irrationalagent I just re-ran this branch locally with @jimporter's lastest and things are looking good to me. 😍 

screen shot 2017-12-07 at 11 18 50 am

Can you please take a look at the doorhanger Telemetry events and make sure they're recording as expected for you, too?

**Comment by irrationalagent** [comment]
looks good to me too. @jimporter thanks so much for your work on this. it will def. help our understanding of how the product is used after we get the Austin bump.

screen shot 2017-12-07 at 12 58 52 pm

**Comment by devinreams** [comment]
As discussed, let's add tests after merge.

**Comment by jimporter** [comment]
Merged after a rebase.

**Pull request merged**
