### PR TITLE
Prepare 0.1.4-alpha and release notes

### PR DESCRIPTION
**Pull request by devinreams**
@sandysage Would you like to work together on the release notes for this version? Some highlights:

- doorhanger will be available
- FxA will replace master password
  - because of FxA, any existing entry data from prior versions is _gone_
- improved UI and Photon goodness

@mozilla-lockbox/engineering can you think of anything else worth highlighting in the notes?

### CODE REVIEW

**Comment by sandysage** [comment]
re: improved UI, I'd also include:
* help and instructions when you first get started (#331)
* links to the new Lockbox website, including the FAQ where you can get additional support (#345)

**Comment by linuxwolf** [comment]
A couple of things to add to "Known Issues":

* After linking to an FxA account, signing into Lockbox with a different account can render it unusable until you quit and restart Firefox.
* Resetting your FxA account password can render Lockbox unusable until you reset Lockbox.

**Comment by linuxwolf** [comment]
@devinreams @sandysage @m8ttyB Updated the "Known Issues" to include warnings about FxA.  Let me know what you think.

**Comment by devinreams** [comment]
Just got an over-the-should approval from @sandysage on the release notes. 👍

**Pull request merged**
