### PR TITLE
Fix modal dialogs

### LINKED ISSUE #162: Clicking "Home" doesn't pop up "Save changes" modal when editing an item

### PR DESCRIPTION
**Pull request by jimporter**
Resolves #162 
only the last 4 commits are unique to this PR.

### CODE REVIEW

**Comment by m8ttyB** [comment]
Entering characters into a new item, deleting those character, and then selecting the `Home` button triggers the unsaved changes dialogue.

STR:
- select `New Entry` button
- enter characters into any input field, then delete those characters
- select the `Home` button

Expected:
The unsaved changes dialogue shouldn't be triggered.

unsaved_changes_hhome_button

**Comment by jimporter** [comment]
> The unsaved changes dialogue shouldn't be triggered.

No, I think it should be triggered. Pretty much every application I've ever worked with does that. (Now, most will revert to "no changes" if you go back via undo, and we don't do that, but that's something we could look at later.)

**Comment by m8ttyB** [comment]
Note, I'm only advocating this for unsaved, new items, that have empty form fields. Entering input into a new, unsaved item should not trigger the unsaved changes modal.

This would also bring the behavior inline with the user flow of selecting 'New Item` and then selecting `Home` without entering any form data.

empty_fields

/cc'ing @changecourse for clarificaiton

**Comment by jimporter** [comment]
@m8ttyB I checked, and this happens on master too, so this isn't the best place to discuss this. Could you file a new issue for it?

**Pull request merged**
