### PR TITLE
I like tests

### PR DESCRIPTION
**Pull request by jimporter**
This is based on my work in #154, so just look at the last 3 commits. This gets us back above 95% test coverage and I think significantly cleans stuff up in our test code.

### CODE REVIEW

**Comment by m8ttyB** [comment]
I've found a state that I can't recover from, attempting to log into Lockbox with the wrong FxA password locks me out of Lockbox.
Steps to reproduce:
- Click the Lockbox toolbar icon, login to FxA with correct password
- Try to log into Lockbox (confirm your Lockbox password modal) using an incorrect password
- Try logging into Lockbox with the correct FxA password
- Close Lockbox tab and click the Lockbox toolbar icon, proceed through the login process again
- The FxA login dialogue sends an authorization code to the users inbox, proceed to enter this
- Attempt to login to the "Confirm your Lockbox Password" modal using the correct password

Outcome, the user cannot login to Lockbox

**Comment by m8ttyB** [comment]
Resizing the browser window also makes navigation of a users items unusable.
screen shot 2017-10-11 at 9 17 38 am

**Comment by devinreams** [comment]
>Outcome, the user cannot login to Lockbox

@m8ttyB If you check out #150 this _should_ be resolved. It's since been merged but may not be incorporated into these branches. Can you checkout a branch and merge master in to confirm?

**Comment by linuxwolf** [comment]
@m8ttyB 

> 've found a state that I can't recover from, attempting to log into Lockbox with the wrong FxA password locks me out of Lockbox.

When you get to this step:

> * Try logging into Lockbox with the correct FxA password

Does that then move you to the "DONE" page, or does it continue to show the same page?

**Comment by m8ttyB** [comment]
When a new entry has been filled out but not saved, should the `Home`
screen shot 2017-10-11 at 9 46 25 am
 button also present the confirmation dialogue presented by the `Cancel` workflow?

**Comment by linuxwolf** [comment]
@m8ttyB A couple of things:

1. Can you open a new issue for the resize problem?  That does not appear to be related to this commit.
2. In trying to reproduce your signin issue (which I still cannot), I'm not sure where you drop off:

> * Try logging into Lockbox with the correct FxA password

Does that succeed or fail?  The rest of your list, it's not clear one way or the other.

**Comment by jimporter** [comment]
Force pushed after rebasing; the only code change I made was to use import aliases in the `<SendFeedback/>` test.

**Pull request merged**
