### PR TITLE
Doorhanger sign-in styling adjustments

### LINKED ISSUE #482: DR: Align doorhanger sign-in to Photon spec
*The doorhanger you see if you are a returning LB user, but are not authenticated*

**Inivision: https://mozilla.invisionapp.com/share/W3EU997YN#/264182186_D_1-1-0_Default_-_Locked_State**

**Zeplin: https://zpl.io/an6g71l**

## Tasks ##
- [x] Match to spec provided in above design (padding, sizing, layout)

### PR DESCRIPTION
**Pull request by nickbrandt**
Resolves #482 
Updated doorhanger sign-in styles to reflect design
Added new button theme and size to account for these buttons as well as others in designs

### CODE REVIEW

**Comment by m8ttyB** [comment]
Verified. Functionally all of the bits work. The designs are converging to what's in invision.
screen shot 2018-02-27 at 1 15 49 pm

**Comment by devinreams** [comment]
>while I don't think the required changes are super esoteric, they do involve a moderate amount of changes to the JS

@jimporter I took a look and am not confident myself in helping chip in and make these changes myself. I think there are two options here:

1. set aside time for you to help make the desired changes and finish this PR
2. merge as-is and open a "refactor" issue to address later

My goal is to speed up the delivery of these changes (ideally by next week's release of 0.1.8) while minimizing how much interruption it requires of you. Thus, I prefer option 2 knowing it may not meet ideal quality standards...

**Comment by jimporter** [comment]
(2) is a no-go. This isn't merge-ready, and I'm not comfortable landing code that needs fixed (especially by someone other than the initial committer) after the fact, since past experience on this project has shown that this falls by the wayside and doesn't get fixed. I'll probably soften on this as we get closer to the Test Pilot release, but for now, I think we have the time available to do things right* the first time.

\* Or if not "right", at least "in a forward-thinking way".

**Comment by devinreams** [comment]
>This isn't merge-ready, and I'm not comfortable landing code that needs fixed (especially by someone other than the initial committer) after the fact ... this falls by the wayside and doesn't get fixed.

@jimporter OK, I'd like to brainstorm ideas with the group on how we can address this. I'll write something up separately and schedule time to discuss it.

That leaves us back with option 1: set aside time for you to help make the desired changes and finish this. I don't mind if you continue this branch or start a separate PR but really want @nickbrandt's hard work incorporated into the release next week. I'll update "assignees" here and in the issue accordingly...

**Comment by m8ttyB** [comment]
Removing `pi-verifed` so I remember to return and re-test this once we land on the path we're going to take.

**Comment by devinreams** [comment]
>Removing pi-verifed so I remember to return and re-test this once we land on the path we're going to take.

FWIW, you can also "Dismiss review" on your own approval review so it just appears as comments and no longer an explicit approval ✅ on the PR itself. 🙃

**Comment by devinreams** [comment]
Thanks for the hard work here, @nickbrandt. This has been superceded by @jimporter's work at #601. 

Nothing personal, just closing this down to relocate the discussion, review and any final changes over there 👉

**Pull request closed without merging**
