### PR TITLE
Prefill the URL in the doorhanger

### LINKED ISSUE #514: Get the URL to the doorhanger and fill it into the search box to provide relevant results for the current URI
Per the notes in #498

At this point, we can just take the hostname (no protocol, no port) for simplicity.

This will probably be handled by pulling the data (i.e. when the doorhanger opens, we'll use WebExtension APIs to grab the active tab's URL and then rip out the bit we care about).

Child of #317

### PR DESCRIPTION
**Pull request by jimporter**
Resolves #514 

I think this is close to done for an initial implementation of the URL prefilling. Perhaps I should move the stuff in `list/popup/index.js` to a separate file so I can write a unit test for it though...

### CODE REVIEW

**Comment by jimporter** [comment]
> Are we okay with not stripping off the `www` in url before putting it into the doorhanger search filter?

Yes. We discussed this a few weeks ago, and improving the URL extraction is #521, which is part 4 of 4 for the URL autofill project. (This is part 1, and I'm starting work today on part 2, which is #520.)

**Comment by m8ttyB** [comment]
Thx @jimporter, yeah this feels like product call. Apologies for not understanding the known limitations, too many child tickets, I missed the nuance of this being broken out across several tickets.

**Comment by m8ttyB** [comment]
Just want to verify one final set of behaviors: if the URI matches an entries site name, site url, or username the door hanger will filter on those entries. Is this this expected per the designs?

screen shot 2018-03-07 at 8 20 34 am

**Comment by linuxwolf** [comment]
@m8ttyB yes, that behavior is expected with this iteration.

This is the first of a number of `task`s that cover the progression to the ideal behavior, as has been covered in planning before.

**Comment by devinreams** [comment]
>There is, however, an argument to be made that this PR should land at the beginning of a release cycle so we have time to fix some of the UX badness

**Comment by devinreams** [comment]
>>There is, however, an argument to be made that this PR should land at the beginning of a release cycle so we have time to fix some of the UX badness

Yup, that's fair. I selfishly wanted it in this release to help speed up my actual day-to-day use of the extension.

@sandysage it's up to you: do you think the "cost" of potential confusion to users outweighs the benefit this initial/progressive feature would offer (convenience when retrieving)?

**Comment by sandysage** [comment]
> do you think the "cost" of potential confusion to users outweighs the benefit this initial/progressive feature would offer (convenience when retrieving)?

As a general rule (that I'm sure we'll break on occasion) let's continue to keeping things moving forward quickly; keeping to our release cycles. We'll capture the WIP state in the release notes, and see how much screaming actually happens :).

**Comment by jimporter** [comment]
Rebased and merged; the only code change was an additional comment as suggested by @linuxwolf

**Pull request merged**
